server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: course-hello-route
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: course-api-route
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/